# https://www.tutorialspoint.com/yaml/yaml_comments.htm

version: 2
jobs:
  build:
    working_directory: ~/notes_app
    docker:
      - image: circleci/ruby:2.3.8-node-browsers
        environment:
          POSTGRES_HOST: localhost
          POSTGRES_USER: notes_app
          RAILS_ENV: test
      - image: postgres:10
        environment:
          POSTGRES_USER: notes_app
          POSTGRES_DB: notes_app_test
          POSTGRES_PASSWORD: ''
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: notes_app-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: notes_app-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run:
          command: |
            bundle exec rails db:create
            bundle exec rails db:structure:load

      # Run the tests
      - run: bundle exec rspec
